# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-06 02:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_dbname', models.CharField(max_length=255, verbose_name='DB Name')),
                ('import_dbname', models.CharField(max_length=255, verbose_name='New DB Name')),
                ('metafile', models.FileField(default='', upload_to='metafiles/', verbose_name='Meta File')),
                ('dba', models.CharField(blank=True, max_length=255, verbose_name='DBA Name')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('imported_yn', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Replay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sql_text', models.TextField(blank=True, verbose_name='SQL TEXT')),
                ('tested_yn', models.BooleanField(default=False)),
                ('suceeded_yn', models.BooleanField(default=False)),
                ('logs', models.TextField(blank=True, verbose_name='LOGS')),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replay_list', to='app.Meta', verbose_name='meta')),
            ],
        ),
        migrations.CreateModel(
            name='ReplayFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('replayfile', models.FileField(default='', upload_to='replayfiles/', verbose_name='Replay File')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_list', to='app.Meta', verbose_name='meta')),
            ],
        ),
    ]
